language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: XQjTBNu2RhFkilZgTYbwBWHa+j4PDZm7lR1nG1zoUJsNXrxKhsLjiJ1ZoeIEaSmP2ae6MNEBBm47h+Nw7TxTV2ahhAf1WirClY0ppxHZiYcWFDlO8EeASa0hxw89jj2u1OjCoVrpiWpIHXOfxruXPkuElnbJDFDj2p+dPBK0C4eI+2zT41Qn+Od+X+OStN0Gpm4C+KWcGszSDmWlPTEVZd2eTVBDjpHPD8h7+T2QX1BRR4HeiENXe50nmi0E9aQdAIKHTjUAcomxiVE621380iXPoT1aRvCCYroF9XUIISRXzSwwWkfRhL6wmpPwqPfqzFGorSj45GxHBOIiLotmrvnET2ickLUPFkr4elqbZeyrYiMmxVdLCAvT3Y8Thp1BDuvEFV07z70H0FJZS5vJ25koEyAkD1gCZHEVzKntU5S2AeFaVQLlw9i+PueWHq6Cj+VviF5Ze91oec2jFhg7JjbQkY8yJ7gN4ilYIHCaIefKxRgwa0IyMl/GOzW2KYTr7JSXUfkwKtUlm0XZeuKPn+/zzPZ9rZqbv6d7JQ6dLOZ1fXlt0LnMkoYuvtbKSNo3icrfUPWWmwfS4FznUBQA70glb9XkvVRVnL9NTwohfSLubttEtF1febmfSWzAOKLLQC2vdJsu6N2L6sf1ZuieoOa5kkYaL/p3cvdm5nZc/2A=
  app: basicwebapp-rain9876
