language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: rmbX9E5UIUolxv/eMtYn3yVqMQchuP84o1bu0ojrPcsOAtK3tHFl54sXgUy3Ratypv3j2itHxveFjgqHexXaDnLfQPqtZ5J6CKEADTTMDfe1WQOCi/huLPBaj6XOOLKkKVRONCsFIHJ0jQtc7f84Ywov7w3V80Qeaz3xV52InZFLqAecY5gSUa/2yT8Xu+Ya1ZuwLlK+E4QkKtNXe3UVIUfFGIvc0+cUTR6uwG4Uvg6iQzBy2vY9WtaQpRy683tCVoyD8mSIesgVo+9MnIF2aokl8pe3iZfXAPfFx3z/mQvWntVfI8O8dQFcLr3GMJhiYmv3lN+znVCkrlAHIEtY9gicmCrtUJ+RniFqu8RZHccX2cSgMQpP4wjDmH2yBbpAbN2FH/OqD7yOTjLaWSjaHrql90xnoIJ2C1BmrKVYRviaIUKnZ6/Cm6a3x/xBfv57TE6x23kWVbJsIpTt52Rjbn1gq4IMwaOfgKOXK5uh9nexOYFGsEZCRjrcTfg4Vf0osn8KNH9V83QRi98HF0X42exMruw7G0oDwHHjP2C3fIs5MUoMqqoL9jt8yyVlzV4mzM1NHOThFHm9cWgr22BgLOkkxOsxrBBK5/8pJZQxx+iZqwrMlLAP8C8tg0UzhsJCQxEp1Dli0mkrI5AcsBOvcvYrMFsMGsPE7/4SJjUpCqU=
