language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: oDm9PRo1BWKboAo4vTDJbF/5Gz1JgLzJmeknD2eFaw1a1HPvYLtL/YYSu/mlYM0c5aR2C0anBFBRuPST9GBrX9hdCHYoq8PdPaOX0NJP2OzKgfZTS+ajm4CyfvX747aXwqPx3LoEiy6eSP1uIl4nRPXiD4LDY5G6slpTQJz/QTSuZI/k3gtNP/D43Pj5m5s/8VgIP5HFDDRJVhe1JMqJXO1bqRw09soKIAUNXKyyh0Dg3pcbjK8n6urlqZilKKe9paAjEL2gIsJqfvT9Q12spd3Ou8MN0djwdBgnaEtaTXLFGdgZKfdCj/qVV0uCVqG6SYUqcxcRDnv5NVjE4EDyKyvTwifS12mzCU/zhliJGcHPCTMEjW4j6wizHkiPC+WLWS1OiHYm0jkPl02vUjY5jnl8I3Pv3WdOBLTYsledwAUzJm3kS2g6efWnDU+zKcUCSMyv2han02elV/1q0s7/uuhArsMNA43W0HqteFRIoW96Kku3E5acQsENA+6DlgUdq1QgZ7mn844O+mmohGP0UHGgt13QfkLf3+YAdb+LD5ntZqrMT9aNktdnMX3KMKeyaHTAyQUoI+EyLpcDvBfGy5+fV0bKw/3SMrQK51OdOr0hTPVNmjJNA4p6+sisRCIwoqvTJTmQz+tPXpcdF0EjZcPOzXNR7n1u5ZZ/g+mXICw=
